stages:

  clean:
    cmd: python src/veri_temizleme.py
    deps:
      - src/veri_temizleme.py
      - data/raw/iris.csv
    outs:
      - data/processed/clean_data.csv
  
  features:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/clean_data.csv
    outs:
      - data/processed/feature_data.csv

  train:
    cmd: python src/model_gelistirme.py
    deps:
      - src/model_gelistirme.py
      - data/processed/feature_data.csv
    outs:
      - models/random_forest.joblib

  optimize:
    cmd: python src/best_model_optimize.py
    deps:
      - src/best_model_optimize.py
      - data/processed/feature_data.csv
    outs:
      - models/best_model.joblib